### ISSUE TITLE
Mismatching versions of commander and commander-extras

### ISSUE THREAD

**Issue by johanblumenberg-symphony** [hash-bang/cli-foreachfile#2]
This package is using `commander` version 4.
It is also using `commander-extras`, which depend on `commander` version 2.

`commander-extras` is working by patching the `commander` package.
Since they depend on different major versions of `commander`, both versions might be installed. `commander-extras` is patching version 2, but `cli-foreachfile` is using version 4, which is not patched.

I don't know why this seems to work when using `npm`. When using `yarn` it fails, because it installs both version 2 and 4.

I would suggest to just drop the dependency to `commander-extras`, since this patching it is doing seems to be a bit unreliable.

**Comment by hash-bang** [comment]
Ah good catch.

I've bumped `commander-extras` and moved its dep on commander to a peerDependency which is how it should have been setup in the first place.

So this should be resolved in `2.0.1`
